server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = / {
        rewrite ^ /public/index.html break;
    }

    location / {
        try_files /public$uri $uri =404;
    }
}
