deploymentMode: SingleBinary

loki:
  auth_enabled: false

singleBinary:
  replicas: 1
  persistence:
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 5Gi

serviceMonitor:
  enabled: true