apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodo-coordinador-hpa
  namespace: apps
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: nodo-coordinador }
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric: { name: http_requests_per_second }
        target: { type: AverageValue, averageValue: "30" }
