apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pool
  namespace: apps
  labels:
    app: node-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-pool
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node-pool
    spec:
      serviceAccountName: blockchain-sa
      # --- SEGMENTACIÓN ---
      nodeSelector:
        role: "app"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      # --------------------------------
      volumes:
        - name: pool-identity
          secret:
            secretName: pool-identity
      containers:
        - name: node-pool
          image: sebajuarez/minerpool:ab1d48f
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: pool-identity
              mountPath: /etc/pool-identity
              readOnly: true
          # --- LÍMITES DE RECURSOS ---
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # ---------------------------
          envFrom:
            - configMapRef:
                name: pool-config
            - secretRef:
                name: pool-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            seccompProfile: { type: RuntimeDefault }