apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: infra
spec:
  serviceName: "rabbitmq-internal"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "infra"
          effect: "NoSchedule"
      # --- SEGMENTACIÓN ---
      nodeSelector:
        role: "infra"
      securityContext:
        fsGroup: 999
      # --------------------------------
      initContainers:
        - name: fix-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "chown -R 999:999 /var/lib/rabbitmq && chmod 600 /var/lib/rabbitmq/.erlang.cookie"]
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          # --- LÍMITES DE RECURSOS ---
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # ---------------------------
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }
            seccompProfile: { type: RuntimeDefault }
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi