apiVersion: v1
kind: Service
metadata:
  name: nodo-coordinador
  namespace: apps
spec:
  type: LoadBalancer

  selector:
    app: nodo-coordinador
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http