apiVersion: v1
kind: Service
metadata:
  name: node-pool
  namespace: apps
spec:
  type: LoadBalancer
  loadBalancerIP: ##IP
  selector:
    app: node-pool
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: http