apiVersion: v1
kind: Service
metadata:
  name: node-pool
  namespace: apps
spec:
  type: LoadBalancer

  selector:
    app: node-pool
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http