name: Docker-Image-Pool Pipeline

on:
  workflow_run:
    workflows: ["Docker-Image-Coordinador Pipeline"]
    types: [completed]
  workflow_dispatch:

env:
  IMAGE_NAME: sebajuarez/minerpool


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Image Tag
      id: vars
      run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      working-directory: coordinator-node/
      run: mvn clean package -DskipTests

    - name: Build and Push Docker Image
      working-directory: coordinator-node/
      run: |
        docker build \
            -t $IMAGE_NAME:${{ steps.vars.outputs.TAG }} .
        docker push $IMAGE_NAME:${{ steps.vars.outputs.TAG }}

    - name: Update Kubernetes Manifests
      run: |
        sed -i "s|image: .*|image: $IMAGE_NAME:${{ steps.vars.outputs.TAG }}|" deploy/deployment/pool-deployment.yaml
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add deploy/deployment/pool-deployment.yaml
        git commit -m "Update image to $IMAGE_NAME:${{ steps.vars.outputs.TAG }}"
        git push
