name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" -backend-config="prefix=${{ secrets.TF_BACKEND_PREFIX }}"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve